import { t, type StringKey } from '../i18n/strings'

export type PhraseTheme = 'general' | 'questions' | 'douceur' | 'quotidien' | 'respiration' | 'nature' | 'emotions' | 'histoires' | 'virelangues'

export const THEMES: readonly PhraseTheme[] = ['general', 'questions', 'douceur', 'quotidien', 'respiration', 'nature', 'emotions', 'histoires', 'virelangues']

export const THEME_LABELS: Record<PhraseTheme, string> = Object.fromEntries(
  THEMES.map(theme => [theme, t(`theme.${theme}` as StringKey)])
) as Record<PhraseTheme, string>

export interface Phrase {
  readonly id: number
  readonly text: string
  readonly theme: PhraseTheme
}

export const PHRASES: readonly Phrase[] = [
  // Général (1000–1049)
  { id: 1000, theme: 'general', text: "Le soleil se lève doucement derrière les montagnes enneigées." },
  { id: 1001, theme: 'general', text: "Les feuilles d'automne tourbillonnent dans le vent frais du matin." },
  { id: 1002, theme: 'general', text: "Une mélodie douce s'échappe par la fenêtre entrouverte." },
  { id: 1003, theme: 'general', text: "Le chat observe tranquillement les oiseaux depuis le rebord." },
  { id: 1004, theme: 'general', text: "Les vagues déferlent sur le sable avec un bruit apaisant." },
  { id: 1005, theme: 'general', text: "Un arôme de café frais emplit la cuisine chaque matin." },
  { id: 1006, theme: 'general', text: "La bibliothèque regorge de récits fascinants à découvrir." },
  { id: 1007, theme: 'general', text: "Des nuages blancs glissent lentement à travers le ciel bleu." },
  { id: 1008, theme: 'general', text: "Le jardin fleuri embaume l'air d'un parfum délicat." },
  { id: 1009, theme: 'general', text: "On entend au loin le carillon d'une vieille horloge." },
  { id: 1010, theme: 'general', text: "La rivière serpente paisiblement entre les prairies verdoyantes." },
  { id: 1011, theme: 'general', text: "Un livre ouvert attend sur la table basse du salon." },
  { id: 1012, theme: 'general', text: "Les étoiles brillent avec intensité par une nuit sans lune." },
  { id: 1013, theme: 'general', text: "Le marché propose des légumes colorés et des herbes fraîches." },
  { id: 1014, theme: 'general', text: "Une pluie légère rafraîchit les rues pavées de la vieille ville." },
  { id: 1015, theme: 'general', text: "Le train traverse des tunnels sombres avant d'atteindre la gare." },
  { id: 1016, theme: 'general', text: "Les enfants jouent avec enthousiasme dans la cour de récréation." },
  { id: 1017, theme: 'general', text: "Un tableau coloré décore le mur principal de la salle." },
  { id: 1018, theme: 'general', text: "La bougie vacille doucement sous l'effet d'un courant d'air." },
  { id: 1019, theme: 'general', text: "Chaque saison apporte ses propres couleurs et ses surprises." },
  { id: 1020, theme: 'general', text: "Le pianiste répète inlassablement le même passage difficile." },
  { id: 1021, theme: 'general', text: "Des pierres plates permettent de traverser le ruisseau à pied sec." },
  { id: 1022, theme: 'general', text: "La terrasse offre une vue magnifique sur les toits du village." },
  { id: 1023, theme: 'general', text: "Un cerf-volant rouge monte haut dans le ciel venteux." },
  { id: 1024, theme: 'general', text: "La forêt dense abrite de nombreuses espèces sauvages discrètes." },
  { id: 1025, theme: 'general', text: "Le boulanger sort du four des miches dorées et croustillantes." },
  { id: 1026, theme: 'general', text: "Une lumière tamisée crée une atmosphère chaleureuse dans la pièce." },
  { id: 1027, theme: 'general', text: "Les cigales chantent sans relâche durant les chaudes journées estivales." },
  { id: 1028, theme: 'general', text: "Le brouillard matinal enveloppe les collines d'un voile mystérieux." },
  { id: 1029, theme: 'general', text: "Un vélo abandonné rouille tranquillement contre la grille du parc." },
  { id: 1030, theme: 'general', text: "La fontaine du quartier gazouille sans interruption depuis des années." },
  { id: 1031, theme: 'general', text: "Des échassiers majestueux longent les berges marécageuses au crépuscule." },
  { id: 1032, theme: 'general', text: "La recette originale nécessite trois ingrédients simples et accessibles." },
  { id: 1033, theme: 'general', text: "Le vent souffle fort ce soir, agitant les branches des peupliers." },
  { id: 1034, theme: 'general', text: "Une exposition temporaire présente des sculptures abstraites surprenantes." },
  { id: 1035, theme: 'general', text: "Les voyageurs attendent patiemment sur le quai bondé de la gare." },
  { id: 1036, theme: 'general', text: "Le téléphone sonne dans la cuisine au moment précis du déjeuner." },
  { id: 1037, theme: 'general', text: "Un sentier forestier mène directement jusqu'au sommet de la colline." },
  { id: 1038, theme: 'general', text: "La neige fraîche recouvre silencieusement les toits et les trottoirs." },
  { id: 1039, theme: 'general', text: "Des photographies anciennes tapissent les murs du couloir principal." },
  { id: 1040, theme: 'general', text: "Le spectacle commence précisément à vingt heures, portes ouvertes à dix-neuf." },
  { id: 1041, theme: 'general', text: "Une clé oubliée traîne sur le bureau depuis plusieurs semaines." },
  { id: 1042, theme: 'general', text: "Les tulipes colorées égayent les parterres du parc municipal." },
  { id: 1043, theme: 'general', text: "Le navigateur consulte sa carte avant d'affronter la haute mer." },
  { id: 1044, theme: 'general', text: "Une odeur de résine flotte dans l'atelier du menuisier artisan." },
  { id: 1045, theme: 'general', text: "La nuit porte conseil, dit-on, pour résoudre les problèmes complexes." },
  { id: 1046, theme: 'general', text: "Le facteur dépose le courrier dans chaque boîte aux lettres rouillée." },
  { id: 1047, theme: 'general', text: "Un aquarium illuminé trône fièrement dans l'entrée du musée." },
  { id: 1048, theme: 'general', text: "Les mouettes tournoient au-dessus du port animé en quête de nourriture." },
  { id: 1049, theme: 'general', text: "La lune pleine éclaire le chemin sinueux menant vers la plaine." },

  // Questions (1100–1149)
  { id: 1100, theme: 'questions', text: "Quel est votre nom ?" },
  { id: 1101, theme: 'questions', text: "Comment tu vas aujourd'hui ?" },
  { id: 1102, theme: 'questions', text: "Tu as bien dormi cette nuit ?" },
  { id: 1103, theme: 'questions', text: "Quelle heure est-il ?" },
  { id: 1104, theme: 'questions', text: "Où habitez-vous ?" },
  { id: 1105, theme: 'questions', text: "Est-ce que tu as mangé ?" },
  { id: 1106, theme: 'questions', text: "C'est loin d'ici ?" },
  { id: 1107, theme: 'questions', text: "Tu viens souvent par ici ?" },
  { id: 1108, theme: 'questions', text: "Qu'est-ce que tu fais dans la vie ?" },
  { id: 1109, theme: 'questions', text: "Il fait beau dehors ?" },
  { id: 1110, theme: 'questions', text: "Tu as besoin d'aide ?" },
  { id: 1111, theme: 'questions', text: "C'est ouvert le dimanche ?" },
  { id: 1112, theme: 'questions', text: "Vous acceptez la carte bancaire ?" },
  { id: 1113, theme: 'questions', text: "Il reste des places disponibles ?" },
  { id: 1114, theme: 'questions', text: "Tu as une recommandation ?" },
  { id: 1115, theme: 'questions', text: "C'est la première fois que tu viens ?" },
  { id: 1116, theme: 'questions', text: "On peut s'asseoir ici ?" },
  { id: 1117, theme: 'questions', text: "Le bus passe souvent ?" },
  { id: 1118, theme: 'questions', text: "Tu connais un bon restaurant dans le coin ?" },
  { id: 1119, theme: 'questions', text: "C'est gratuit ?" },
  { id: 1120, theme: 'questions', text: "Vous avez ce livre en stock ?" },
  { id: 1121, theme: 'questions', text: "Je peux essayer ?" },
  { id: 1122, theme: 'questions', text: "Tu as vu mes clés quelque part ?" },
  { id: 1123, theme: 'questions', text: "On arrive à quelle heure ?" },
  { id: 1124, theme: 'questions', text: "C'est toi qui as appelé ?" },
  { id: 1125, theme: 'questions', text: "Tu peux répéter plus lentement ?" },
  { id: 1126, theme: 'questions', text: "Il y a une pharmacie près d'ici ?" },
  { id: 1127, theme: 'questions', text: "Vous avez une table pour deux personnes ?" },
  { id: 1128, theme: 'questions', text: "C'est compris dans le prix ?" },
  { id: 1129, theme: 'questions', text: "Tu veux qu'on y aille ensemble ?" },
  { id: 1130, theme: 'questions', text: "Le trajet dure combien de temps ?" },
  { id: 1131, theme: 'questions', text: "Est-ce que c'est possible de changer la date ?" },
  { id: 1132, theme: 'questions', text: "Tu as déjà essayé ça ?" },
  { id: 1133, theme: 'questions', text: "On peut se garer facilement ?" },
  { id: 1134, theme: 'questions', text: "Vous avez d'autres couleurs ?" },
  { id: 1135, theme: 'questions', text: "C'est la bonne direction ?" },
  { id: 1136, theme: 'questions', text: "Tu te souviens de son prénom ?" },
  { id: 1137, theme: 'questions', text: "Il y a du réseau ici ?" },
  { id: 1138, theme: 'questions', text: "Quelqu'un a commandé du café ?" },
  { id: 1139, theme: 'questions', text: "Tu veux bien me garder une place ?" },
  { id: 1140, theme: 'questions', text: "C'est encore disponible ?" },
  { id: 1141, theme: 'questions', text: "Tu as le numéro de téléphone ?" },
  { id: 1142, theme: 'questions', text: "On peut payer en plusieurs fois ?" },
  { id: 1143, theme: 'questions', text: "Vous livrez à domicile ?" },
  { id: 1144, theme: 'questions', text: "Tu as déjà visité cette ville ?" },
  { id: 1145, theme: 'questions', text: "Il est possible de reporter le rendez-vous ?" },
  { id: 1146, theme: 'questions', text: "Tu préfères le matin ou l'après-midi ?" },
  { id: 1147, theme: 'questions', text: "C'est encore loin ?" },
  { id: 1148, theme: 'questions', text: "On se retrouve à quelle station ?" },
  { id: 1149, theme: 'questions', text: "Tu as passé une bonne journée ?" },

  // Voix douce (1200–1249)
  { id: 1200, theme: 'douceur', text: "La lumière filtre doucement à travers les feuilles." },
  { id: 1201, theme: 'douceur', text: "Une voix douce murmure des mots apaisants." },
  { id: 1202, theme: 'douceur', text: "L'eau coule lentement sur les pierres lisses." },
  { id: 1203, theme: 'douceur', text: "Le velours effleure ma main avec douceur." },
  { id: 1204, theme: 'douceur', text: "La brume matinale enveloppe la vallée sereine." },
  { id: 1205, theme: 'douceur', text: "Un souffle léger anime les fleurs du matin." },
  { id: 1206, theme: 'douceur', text: "La soie glisse sur ma peau avec sérénité." },
  { id: 1207, theme: 'douceur', text: "Mes mains reposent sur la surface lisse." },
  { id: 1208, theme: 'douceur', text: "La lune illumine le lac avec une lumière douce." },
  { id: 1209, theme: 'douceur', text: "Le murmure du vent me berce doucement." },
  { id: 1210, theme: 'douceur', text: "Une mélodie douce emplit l'air du salon." },
  { id: 1211, theme: 'douceur', text: "Les nuages flottent avec légèreté dans le ciel." },
  { id: 1212, theme: 'douceur', text: "La rivière reflète les couleurs du soir." },
  { id: 1213, theme: 'douceur', text: "Une lumière dorée réchauffe la pièce silencieuse." },
  { id: 1214, theme: 'douceur', text: "Le miel coule lentement, doré et lumineux." },
  { id: 1215, theme: 'douceur', text: "Les feuilles frémissent sous la brise légère." },
  { id: 1216, theme: 'douceur', text: "La nuit enveloppe le monde de velours sombre." },
  { id: 1217, theme: 'douceur', text: "Mon souffle se pose, calme et régulier." },
  { id: 1218, theme: 'douceur', text: "La fleur s'ouvre lentement vers la lumière." },
  { id: 1219, theme: 'douceur', text: "Une voix bienveillante m'accompagne avec soin." },
  { id: 1220, theme: 'douceur', text: "Le sable fin glisse entre mes doigts ouverts." },
  { id: 1221, theme: 'douceur', text: "La lavande emplit l'air d'un parfum serein." },
  { id: 1222, theme: 'douceur', text: "L'aurore nimbe la forêt d'une lueur rose." },
  { id: 1223, theme: 'douceur', text: "Les mots coulent, fluides et sans effort." },
  { id: 1224, theme: 'douceur', text: "Une main douce effleure mon épaule avec tendresse." },
  { id: 1225, theme: 'douceur', text: "Le silence se pose comme un voile léger." },
  { id: 1226, theme: 'douceur', text: "La flamme vacille, lumineuse et apaisante." },
  { id: 1227, theme: 'douceur', text: "Mon cœur s'ouvre à la bienveillance du monde." },
  { id: 1228, theme: 'douceur', text: "La neige recouvre la vallée d'un manteau blanc." },
  { id: 1229, theme: 'douceur', text: "Les sons s'évanoissent dans un silence velours." },
  { id: 1230, theme: 'douceur', text: "Une lumière douce illumine mon visage serein." },
  { id: 1231, theme: 'douceur', text: "La voile flotte, légère sur l'eau calme." },
  { id: 1232, theme: 'douceur', text: "Le lin frais effleure ma joue avec douceur." },
  { id: 1233, theme: 'douceur', text: "Les étoiles veillent sur la nuit silencieuse." },
  { id: 1234, theme: 'douceur', text: "Une rosée fine perle sur les feuilles vertes." },
  { id: 1235, theme: 'douceur', text: "Le ronronnement apaisant emplit la pièce douce." },
  { id: 1236, theme: 'douceur', text: "Ma voix se pose, fluide et sereine." },
  { id: 1237, theme: 'douceur', text: "Les vagues murmurent une berceuse au rivage." },
  { id: 1238, theme: 'douceur', text: "Un sourire lumineux réchauffe le cœur froid." },
  { id: 1239, theme: 'douceur', text: "La soie effleure l'air avec légèreté infinie." },
  { id: 1240, theme: 'douceur', text: "Le matin se lève, rosé et sans nuages." },
  { id: 1241, theme: 'douceur', text: "La lumière de la lune nimbe tout de douceur." },
  { id: 1242, theme: 'douceur', text: "Les rires légers se mêlent au vent frais." },
  { id: 1243, theme: 'douceur', text: "Une brise marine soulève les cheveux fins." },
  { id: 1244, theme: 'douceur', text: "Le fil de soie relie deux mains bienveillantes." },
  { id: 1245, theme: 'douceur', text: "La lumière filtrée invite au calme intérieur." },
  { id: 1246, theme: 'douceur', text: "Les mots fleurissent, doux comme un soupir." },
  { id: 1247, theme: 'douceur', text: "Mon souffle murmure une promesse de sérénité." },
  { id: 1248, theme: 'douceur', text: "La nuit bienveillante enveloppe l'âme en paix." },
  { id: 1249, theme: 'douceur', text: "Une lumière intérieure rayonne avec une douceur infinie." },

  // Quotidien (1300–1349)
  { id: 1300, theme: 'quotidien', text: "Je vais faire les courses, tu as besoin de quelque chose ?" },
  { id: 1301, theme: 'quotidien', text: "Le café est prêt, tu en veux une tasse ?" },
  { id: 1302, theme: 'quotidien', text: "J'ai raté le bus ce matin." },
  { id: 1303, theme: 'quotidien', text: "Il faut que je passe à la pharmacie avant de rentrer." },
  { id: 1304, theme: 'quotidien', text: "On mange à quelle heure ce soir ?" },
  { id: 1305, theme: 'quotidien', text: "La connexion internet est encore en train de couper !" },
  { id: 1306, theme: 'quotidien', text: "Tu peux me passer le sel, s'il te plaît ?" },
  { id: 1307, theme: 'quotidien', text: "J'ai passé toute la matinée à faire le ménage." },
  { id: 1308, theme: 'quotidien', text: "Le supermarché ferme dans vingt minutes." },
  { id: 1309, theme: 'quotidien', text: "Je suis épuisé après cette journée de travail." },
  { id: 1310, theme: 'quotidien', text: "Il pleut encore, j'aurais dû prendre mon parapluie !" },
  { id: 1311, theme: 'quotidien', text: "Je n'arrive plus à retrouver où j'ai mis mon agenda." },
  { id: 1312, theme: 'quotidien', text: "Je prends un café noir, sans sucre." },
  { id: 1313, theme: 'quotidien', text: "On se retrouve à la sortie du métro à dix-huit heures." },
  { id: 1314, theme: 'quotidien', text: "J'ai oublié de recharger mon téléphone cette nuit." },
  { id: 1315, theme: 'quotidien', text: "Le trajet était vraiment long aujourd'hui." },
  { id: 1316, theme: 'quotidien', text: "Tu veux qu'on commande à manger ce soir ?" },
  { id: 1317, theme: 'quotidien', text: "J'ai une réunion en ligne à quatorze heures." },
  { id: 1318, theme: 'quotidien', text: "La machine à laver a terminé son cycle." },
  { id: 1319, theme: 'quotidien', text: "Je dois rendre ce rapport avant vendredi." },
  { id: 1320, theme: 'quotidien', text: "On manque de lait, je vais en racheter." },
  { id: 1321, theme: 'quotidien', text: "Le chat a encore renversé son bol d'eau !" },
  { id: 1322, theme: 'quotidien', text: "J'ai enfin trouvé une place pour me garer." },
  { id: 1323, theme: 'quotidien', text: "Tu peux baisser le volume un peu ?" },
  { id: 1324, theme: 'quotidien', text: "Je fais une pause, je reviens dans cinq minutes." },
  { id: 1325, theme: 'quotidien', text: "Le boulanger n'avait plus de croissants ce matin." },
  { id: 1326, theme: 'quotidien', text: "J'ai travaillé depuis chez moi toute la semaine." },
  { id: 1327, theme: 'quotidien', text: "On a prévu de se voir samedi avec les amis." },
  { id: 1328, theme: 'quotidien', text: "Il fait vraiment chaud pour un mois de juin !" },
  { id: 1329, theme: 'quotidien', text: "J'ai encore une pile de linge à repasser." },
  { id: 1330, theme: 'quotidien', text: "Tu connais un bon restaurant dans le quartier ?" },
  { id: 1331, theme: 'quotidien', text: "Je me suis levé tard ce matin, j'avais besoin de sommeil." },
  { id: 1332, theme: 'quotidien', text: "Les transports en commun étaient bondés à cette heure-là." },
  { id: 1333, theme: 'quotidien', text: "J'ai fini par commander en ligne." },
  { id: 1334, theme: 'quotidien', text: "Tu viens avec nous au marché dimanche ?" },
  { id: 1335, theme: 'quotidien', text: "J'ai besoin de faire une sieste, je suis à plat." },
  { id: 1336, theme: 'quotidien', text: "Le dîner était vraiment délicieux hier soir !" },
  { id: 1337, theme: 'quotidien', text: "J'attends un colis depuis une semaine." },
  { id: 1338, theme: 'quotidien', text: "Tu peux m'envoyer l'adresse par message ?" },
  { id: 1339, theme: 'quotidien', text: "J'ai croisé des voisins en sortant de l'immeuble." },
  { id: 1340, theme: 'quotidien', text: "Il faut qu'on pense à payer la facture d'électricité." },
  { id: 1341, theme: 'quotidien', text: "Je vais me faire un thé, ça me détend." },
  { id: 1342, theme: 'quotidien', text: "La file d'attente à la caisse était interminable !" },
  { id: 1343, theme: 'quotidien', text: "J'ai relu le mail trois fois avant de l'envoyer." },
  { id: 1344, theme: 'quotidien', text: "On peut passer par le parc pour rentrer ?" },
  { id: 1345, theme: 'quotidien', text: "Je n'arrive pas à me concentrer avec ce bruit." },
  { id: 1346, theme: 'quotidien', text: "Tu as pensé à annuler l'abonnement ?" },
  { id: 1347, theme: 'quotidien', text: "J'ai passé la soirée à ranger et à trier des affaires." },
  { id: 1348, theme: 'quotidien', text: "Le week-end est passé beaucoup trop vite !" },
  { id: 1349, theme: 'quotidien', text: "Je suis content de rentrer à la maison ce soir." },

  // Souffle (1400–1449)
  { id: 1400, theme: 'respiration', text: "Le soleil se couchait lentement derrière les collines dorées, teintant le ciel de nuances de rose et d'orangé qui se reflétaient sur la surface calme du lac." },
  { id: 1401, theme: 'respiration', text: "Les feuilles des arbres frémissaient doucement sous la brise légère de l'après-midi, créant un murmure apaisant qui se mêlait au chant lointain des oiseaux." },
  { id: 1402, theme: 'respiration', text: "Dans la bibliothèque silencieuse, l'odeur des vieux livres se répandait comme une invitation au voyage, rappelant les histoires et les aventures que chaque page avait traversées au fil du temps." },
  { id: 1403, theme: 'respiration', text: "La rivière coulait paisiblement entre les pierres rondes et lisses, portant avec elle les reflets du ciel bleu et les ombres dansantes des saules qui bordaient ses rives." },
  { id: 1404, theme: 'respiration', text: "Chaque matin, la lumière dorée filtrait à travers les rideaux de lin blanc et venait réchauffer les planchers de bois patiné où s'étiraient les premières heures du jour." },
  { id: 1405, theme: 'respiration', text: "Les vagues venaient mourir sur le sable fin avec un souffle régulier et doux, comme la respiration lente d'un être endormi au bord de l'immensité bleue de l'océan." },
  { id: 1406, theme: 'respiration', text: "Au fil des saisons, le jardin se transformait sans cesse, offrant tour à tour des fleurs éclatantes au printemps et des teintes cuivrées à l'automne sous le ciel changeant." },
  { id: 1407, theme: 'respiration', text: "La pluie tombait en rideau sur les toits de tuiles, remplissant les ruelles pavées d'un bruissement régulier et frais qui lavait l'air de toutes ses poussières accumulées." },
  { id: 1408, theme: 'respiration', text: "Une longue avenue bordée de platanes aux troncs argentés s'étirait à perte de vue, offrant une ombre généreuse aux promeneurs qui avançaient dans la chaleur douce de l'été." },
  { id: 1409, theme: 'respiration', text: "Les nuages voyageaient lentement au-dessus des plaines, projetant des ombres mouvantes sur les champs de blé qui ondulaient comme une mer verte et dorée sous le vent tiède." },
  { id: 1410, theme: 'respiration', text: "Dans la cuisine chaude et parfumée, les effluves de cannelle et de vanille se mêlaient harmonieusement, enveloppant tous ceux qui s'y trouvaient d'une sensation de douceur et de réconfort profond." },
  { id: 1411, theme: 'respiration', text: "Le chemin de terre serpentait entre les vignes avant de rejoindre le village perché sur la colline, dont les maisons de pierre ocre brillaient sous la lumière de fin d'après-midi." },
  { id: 1412, theme: 'respiration', text: "Le son du violoncelle emplissait la salle de concert d'une vibration chaude et profonde qui semblait toucher quelque chose d'essentiel dans chacun des auditeurs silencieusement réunis ce soir-là." },
  { id: 1413, theme: 'respiration', text: "Au loin, les montagnes enneigées se découpaient avec une précision remarquable sur le fond d'un ciel d'une pureté absolue, témoignant de la grandeur sereine et immuable de la nature." },
  { id: 1414, theme: 'respiration', text: "Le marché du dimanche matin réunissait dans une joyeuse animation les habitants du quartier, attirés par les couleurs vives des étals de fruits, de légumes et de fleurs fraîches." },
  { id: 1415, theme: 'respiration', text: "Une lumière douce et uniforme baignait l'atelier de l'artisan, révélant sur sa table les outils soigneusement disposés et le bois clair qu'il allait sculpter avec patience et précision tout au long de la journée." },
  { id: 1416, theme: 'respiration', text: "Le soir venu, les étoiles apparaissaient une à une dans le ciel qui s'assombrissait progressivement, formant peu à peu la carte lumineuse que les navigateurs d'autrefois suivaient avec confiance." },
  { id: 1417, theme: 'respiration', text: "Les hirondelles décrivaient leurs arabesques gracieuses dans le ciel du soir, plongeant et remontant avec une aisance parfaite avant de regagner leurs nids sous les avancées des toits." },
  { id: 1418, theme: 'respiration', text: "La brume matinale enveloppait la vallée d'un voile laiteux et transparent qui se dissiperait bientôt sous l'effet des premiers rayons du soleil levant sur les crêtes boisées." },
  { id: 1419, theme: 'respiration', text: "Le train glissait doucement entre les collines verdoyantes, offrant à ses passagers des paysages changeants qui se succédaient derrière les vitres comme les pages d'un livre ouvert sur le monde." },
  { id: 1420, theme: 'respiration', text: "Le parfum des roses anciennes se diffusait dans tout le jardin et portait avec lui une douceur mélancolique, comme un souvenir d'étés anciens que l'on retrouve avec une joie émue." },
  { id: 1421, theme: 'respiration', text: "Sur la terrasse ensoleillée, le thé fumant répandait ses arômes délicats de jasmin et de bergamote, invitant à la pause et à la contemplation tranquille de l'horizon bleu et lointain." },
  { id: 1422, theme: 'respiration', text: "Les enfants couraient librement dans les allées du parc, leurs rires clairs se mêlant au bruit des jets d'eau et au froissement des feuilles que le vent remuait doucement." },
  { id: 1423, theme: 'respiration', text: "La vieille horloge au coin de la rue égrainait les heures avec une régularité rassurante, rappelant à chaque passant que le temps avance toujours, même aux jours les plus doux." },
  { id: 1424, theme: 'respiration', text: "Le clapotis de l'eau sur la coque du bateau créait une mélodie irrégulière et hypnotique que l'on écoutait les yeux mi-clos, bercé par le mouvement lent et régulier des vagues." },
  { id: 1425, theme: 'respiration', text: "Dans la forêt dense et silencieuse, seuls quelques rais de lumière parvenaient à traverser la canopée épaisse pour venir éclairer les mousses et les fougères du sous-bois humide." },
  { id: 1426, theme: 'respiration', text: "La lumière de la lune posait sur le jardin endormi une clarté bleue et froide qui transformait les formes familières en silhouettes mystérieuses et doucement inquiétantes dans l'air immobile de la nuit." },
  { id: 1427, theme: 'respiration', text: "Les pages du livre que l'on lisait ce soir-là se tournaient lentement, chaque paragraphe offrant une nouvelle image, une nouvelle sensation, un monde entier contenu dans l'espace de quelques lignes bien choisies." },
  { id: 1428, theme: 'respiration', text: "Le vent du nord apportait avec lui une fraîcheur vivifiante et l'odeur de la pluie prochaine, soulevant les herbes hautes des champs et faisant vibrer les fils du téléphone le long de la route." },
  { id: 1429, theme: 'respiration', text: "Au bord du chemin, une source minuscule faisait naître un filet d'eau cristalline qui descendait en murmurant entre les pierres couvertes de mousse jusqu'au ruisseau en contrebas de la prairie." },
  { id: 1430, theme: 'respiration', text: "Les voix du chœur s'élevaient dans la nef de la cathédrale, amplifiées par la pierre ancienne et l'espace vaste, créant une harmonie puissante et lumineuse qui semblait remplir chaque recoin de l'édifice." },
  { id: 1431, theme: 'respiration', text: "La promenade longeait la falaise et offrait à intervalles réguliers des échappées sur la mer d'un bleu profond, où l'on devinait au loin la silhouette d'un cargo suivant lentement son cap." },
  { id: 1432, theme: 'respiration', text: "Les fleurs sauvages poussaient librement au bord des chemins agricoles, indifférentes aux saisons et aux passages, offrant leur beauté simple et généreuse à qui prenait la peine de les regarder." },
  { id: 1433, theme: 'respiration', text: "Le café du matin se dégustait lentement sur le balcon, face à la rue encore peu animée, pendant que la ville s'éveillait progressivement dans la lumière dorée et fraîche de l'aurore." },
  { id: 1434, theme: 'respiration', text: "Une vague de chaleur douce et parfumée enveloppait les visiteurs dès l'entrée dans la serre tropicale, où les grandes feuilles luisantes et les fleurs exotiques créaient un univers d'une densité végétale envoûtante." },
  { id: 1435, theme: 'respiration', text: "Le pianiste laissait ses doigts courir sur les touches avec une légèreté apparente qui cachait des années de travail patient, donnant à la mélodie une fluidité naturelle et une douceur touchante." },
  { id: 1436, theme: 'respiration', text: "Les toits de la vieille ville formaient un paysage de tuiles rouges et de cheminées que la lumière rasante du soir transformait en une composition de volumes et d'ombres aux tonalités chaudes." },
  { id: 1437, theme: 'respiration', text: "La nuit avançait doucement sur la campagne, éteignant une à une les lumières des fermes isolées et laissant le champ libre aux étoiles qui brillaient avec une intensité étonnante dans l'obscurité totale." },
  { id: 1438, theme: 'respiration', text: "Le lichen gris et vert couvrait les vieux murs de pierres sèches, témoignant du temps long qui avait coulé depuis leur construction et de la patience silencieuse avec laquelle la nature reprend ses droits." },
  { id: 1439, theme: 'respiration', text: "Les abeilles bourdonnaient avec régularité parmi les fleurs du tilleul en fleur, portant leur récolte parfumée jusqu'à la ruche dont on entendait la vibration grave et continue depuis le fond du jardin." },
  { id: 1440, theme: 'respiration', text: "Le regard se perdait à l'horizon sur cette étendue d'eau immobile qui reflétait le ciel avec une fidélité parfaite, effaçant toute frontière entre le haut et le bas, entre l'eau et l'air." },
  { id: 1441, theme: 'respiration', text: "La vieille maison familiale avait gardé l'odeur des années passées, un mélange subtil de bois ciré, de livres anciens et de cuisine épicée qui ramenait instantanément à l'enfance ceux qui la reconnaissaient." },
  { id: 1442, theme: 'respiration', text: "Les moutons traversaient le chemin en un long défilé lent et laineux, ignorant superbement les voitures arrêtées dont les conducteurs regardaient passer ce troupeau avec un sourire de surprise amusée." },
  { id: 1443, theme: 'respiration', text: "La lumière filtrait à travers les branches entrelacées des hêtres et créait sur le sol de la forêt un damier mouvant de taches lumineuses et d'ombres fraîches que le vent animait sans cesse." },
  { id: 1444, theme: 'respiration', text: "On entendait de loin le son des cloches qui marquaient l'heure dans le clocher du village, portés par le vent jusqu'aux prés où les herbes fraîches ondulaient sous le soleil de midi." },
  { id: 1445, theme: 'respiration', text: "La côte découpée offrait une succession de criques et de caps rocheux que l'on découvrait au fil de la marche, chaque tournant révélant un nouveau tableau de mer, de falaise et de ciel." },
  { id: 1446, theme: 'respiration', text: "Le feu dans la cheminée crépitait doucement, projetant sur les murs de la pièce des reflets orange et dorés qui dansaient en silence pendant que dehors le vent soufflait sur les volets fermés." },
  { id: 1447, theme: 'respiration', text: "Les pavés mouillés de la ruelle réfléchissaient les lumières des enseignes colorées, créant sur le sol un tableau abstrait et changeant que les passants traversaient sans lui accorder un regard." },
  { id: 1448, theme: 'respiration', text: "La traversée en ferry durait une heure, pendant laquelle on pouvait observer les mouettes qui planaient sans effort apparent, portées par les courants d'air chaud au-dessus du sillage blanc du bateau." },
  { id: 1449, theme: 'respiration', text: "Les grandes orgues de la cathédrale se mirent à résonner dans toute la nef, emplissant l'espace d'une masse sonore profonde et vibrante qui semblait faire trembler l'air lui-même jusqu'aux voûtes les plus hautes." },

  // Nature (1500–1549)
  { id: 1500, theme: 'nature', text: "La forêt baigne dans une lumière dorée et apaisante." },
  { id: 1501, theme: 'nature', text: "Les vagues roulent doucement sur le sable chaud de la plage." },
  { id: 1502, theme: 'nature', text: "Au printemps, les fleurs sauvages tapissent les prairies de couleurs." },
  { id: 1503, theme: 'nature', text: "La montagne se drape d'un manteau blanc sous la neige abondante." },
  { id: 1504, theme: 'nature', text: "Les oiseaux chantent dans les branches au cœur du matin calme." },
  { id: 1505, theme: 'nature', text: "L'automne répand ses teintes orangées sur les feuilles tombantes." },
  { id: 1506, theme: 'nature', text: "Le lac reflète le ciel bleu et les nuages blancs comme un miroir." },
  { id: 1507, theme: 'nature', text: "Les papillons volent de fleur en fleur dans le jardin ensoleillé." },
  { id: 1508, theme: 'nature', text: "La pluie d'été tambourine doucement sur les larges feuilles du chêne." },
  { id: 1509, theme: 'nature', text: "Un renard roux traverse la clairière au crépuscule rosé." },
  { id: 1510, theme: 'nature', text: "Les étoiles parsèment le ciel noir d'une clarté froide et lointaine." },
  { id: 1511, theme: 'nature', text: "La rivière murmure entre les cailloux ronds et les mousses vertes." },
  { id: 1512, theme: 'nature', text: "Au sommet de la colline, le vent chante dans les herbes hautes." },
  { id: 1513, theme: 'nature', text: "Les lavandes embaument l'air chaud du mois de juillet." },
  { id: 1514, theme: 'nature', text: "La mer étale son manteau de turquoise jusqu'à l'horizon flou." },
  { id: 1515, theme: 'nature', text: "Les grues cendrées traversent le ciel en formation serrée." },
  { id: 1516, theme: 'nature', text: "La brume du matin enveloppe la vallée d'un voile transparent." },
  { id: 1517, theme: 'nature', text: "Les pommes tombent avec un bruit sourd dans l'herbe mouillée." },
  { id: 1518, theme: 'nature', text: "Un cerf majestueux s'arrête au bord du chemin forestier." },
  { id: 1519, theme: 'nature', text: "La neige recouvre les toits et les jardins d'un silence ouaté." },
  { id: 1520, theme: 'nature', text: "Les roses du jardin s'ouvrent lentement sous la chaleur de l'aurore." },
  { id: 1521, theme: 'nature', text: "L'océan gronde et écume sous le ciel chargé d'orages lointains." },
  { id: 1522, theme: 'nature', text: "Les bouleaux tremblent dans la brise fraîche du soir d'automne." },
  { id: 1523, theme: 'nature', text: "Un vol d'étourneaux dessine des arabesques dans le ciel orangé." },
  { id: 1524, theme: 'nature', text: "La cascade tombe en nappe blanche dans le bassin de rochers." },
  { id: 1525, theme: 'nature', text: "Les abricots dorés mûrissent au soleil sur les branches basses." },
  { id: 1526, theme: 'nature', text: "La lune éclaire le chemin d'argent dans la nuit tranquille." },
  { id: 1527, theme: 'nature', text: "Les fourmis tracent leurs routes invisibles dans la terre chaude." },
  { id: 1528, theme: 'nature', text: "L'horizon de la mer fond dans le ciel au moment du coucher de soleil." },
  { id: 1529, theme: 'nature', text: "Les bourgeons roses annoncent le retour du printemps avec douceur." },
  { id: 1530, theme: 'nature', text: "La forêt de sapins embaume l'air froid d'un parfum de résine." },
  { id: 1531, theme: 'nature', text: "Les canards barbotent dans l'eau verte de l'étang du village." },
  { id: 1532, theme: 'nature', text: "Un arc-en-ciel traverse le ciel après l'averse de l'après-midi." },
  { id: 1533, theme: 'nature', text: "Les blés dorés ondulent comme une mer sous le vent d'été." },
  { id: 1534, theme: 'nature', text: "La corneille pose son regard noir sur la branche nue du chêne." },
  { id: 1535, theme: 'nature', text: "Les pétales de cerisier tombent en pluie rose sur le sol mouillé." },
  { id: 1536, theme: 'nature', text: "La montagne se colore de mauve au coucher du soleil d'hiver." },
  { id: 1537, theme: 'nature', text: "Les abeilles bourdonnent dans les fleurs sauvages du bord de route." },
  { id: 1538, theme: 'nature', text: "La marée monte lentement et engloutit les rochers du rivage." },
  { id: 1539, theme: 'nature', text: "Les feuilles mortes craquent sous les pas dans l'allée du parc." },
  { id: 1540, theme: 'nature', text: "Un aigle plane haut dans le ciel bleu au-dessus des crêtes rocheuses." },
  { id: 1541, theme: 'nature', text: "La rosée du matin perle sur les toiles d'araignée entre les herbes." },
  { id: 1542, theme: 'nature', text: "Les grands peupliers se balancent doucement au bord du canal." },
  { id: 1543, theme: 'nature', text: "L'aurore teinte les nuages de rose, d'orange et de rouge profond." },
  { id: 1544, theme: 'nature', text: "Les champignons poussent en cercle dans le sous-bois humide et sombre." },
  { id: 1545, theme: 'nature', text: "La brise marine apporte l'odeur du sel et des algues séchées." },
  { id: 1546, theme: 'nature', text: "Les libellules bleues rasent la surface calme de l'étang au soir." },
  { id: 1547, theme: 'nature', text: "La vallée s'endort sous un ciel d'étoiles sans fond ni limite." },
  { id: 1548, theme: 'nature', text: "Les tournesols tournent leur visage doré vers la lumière chaude du midi." },
  { id: 1549, theme: 'nature', text: "La forêt respire lentement au rythme des saisons qui passent." },

  // Émotions (1600–1649)
  { id: 1600, theme: 'emotions', text: "Ce moment est exactement comme je l'avais imaginé." },
  { id: 1601, theme: 'emotions', text: "Oh, je n'aurais jamais cru que ça marcherait !" },
  { id: 1602, theme: 'emotions', text: "Il y a quelque chose de doux dans ce silence." },
  { id: 1603, theme: 'emotions', text: "Je déborde d'énergie aujourd'hui, c'est incroyable !" },
  { id: 1604, theme: 'emotions', text: "Cette lumière du soir me donne envie de rester là." },
  { id: 1605, theme: 'emotions', text: "Je suis tellement fier de ce que j'ai accompli." },
  { id: 1606, theme: 'emotions', text: "Attends, tu veux dire que c'est pour moi ?" },
  { id: 1607, theme: 'emotions', text: "Quelque chose dans cette musique me touche profondément." },
  { id: 1608, theme: 'emotions', text: "Je n'arrive pas à croire que c'est enfin arrivé." },
  { id: 1609, theme: 'emotions', text: "Il y a un espoir fragile, mais il est là." },
  { id: 1610, theme: 'emotions', text: "Comme c'est bon de se retrouver ensemble !" },
  { id: 1611, theme: 'emotions', text: "Cette odeur me ramène des années en arrière." },
  { id: 1612, theme: 'emotions', text: "Je sens que quelque chose de beau est en train de commencer." },
  { id: 1613, theme: 'emotions', text: "Vraiment ? Mais c'est fantastique, cette nouvelle !" },
  { id: 1614, theme: 'emotions', text: "J'ai le cœur léger ce matin, sans raison précise." },
  { id: 1615, theme: 'emotions', text: "Cette photo me manque, comme l'époque qu'elle représente." },
  { id: 1616, theme: 'emotions', text: "Je pourrais rire pendant des heures tellement c'est drôle." },
  { id: 1617, theme: 'emotions', text: "Quelle douceur dans ce geste, je ne l'oublierai pas." },
  { id: 1618, theme: 'emotions', text: "C'est étrange, je me sens exactement à ma place ici." },
  { id: 1619, theme: 'emotions', text: "Tout à coup, tout semblait possible et lumineux." },
  { id: 1620, theme: 'emotions', text: "Je n'aurais jamais osé espérer un tel résultat." },
  { id: 1621, theme: 'emotions', text: "Il y a une mélancolie tranquille dans ce paysage d'automne." },
  { id: 1622, theme: 'emotions', text: "Mon cœur s'est mis à battre plus vite sans prévenir." },
  { id: 1623, theme: 'emotions', text: "Parfois, la tendresse se passe de mots." },
  { id: 1624, theme: 'emotions', text: "Je suis stupéfait — c'est bien la dernière chose que j'attendais !" },
  { id: 1625, theme: 'emotions', text: "Ce calme après la tempête est presque irréel." },
  { id: 1626, theme: 'emotions', text: "J'ai tellement hâte que tu voies ce que j'ai préparé." },
  { id: 1627, theme: 'emotions', text: "Il y a quelque chose d'émouvant dans les dernières pages d'un livre." },
  { id: 1628, theme: 'emotions', text: "Je ris encore rien que d'y penser." },
  { id: 1629, theme: 'emotions', text: "Cette confiance que tu me donnes, je la chéris." },
  { id: 1630, theme: 'emotions', text: "Mais comment as-tu su que c'était exactement ça qu'il me fallait ?" },
  { id: 1631, theme: 'emotions', text: "Un brin de nostalgie, mais surtout beaucoup de gratitude." },
  { id: 1632, theme: 'emotions', text: "Je veux garder ce souvenir intact le plus longtemps possible." },
  { id: 1633, theme: 'emotions', text: "L'enthousiasme dans la salle était absolument contagieux." },
  { id: 1634, theme: 'emotions', text: "Je me sens serein, pour la première fois depuis longtemps." },
  { id: 1635, theme: 'emotions', text: "C'est incroyable comme une petite victoire peut tout changer." },
  { id: 1636, theme: 'emotions', text: "J'ai les larmes aux yeux, mais de joie cette fois." },
  { id: 1637, theme: 'emotions', text: "Quelque chose en moi s'est déposé, apaisé." },
  { id: 1638, theme: 'emotions', text: "Oh là là, je ne m'y attendais vraiment pas du tout !" },
  { id: 1639, theme: 'emotions', text: "Cette fierté discrète, je la savoure en silence." },
  { id: 1640, theme: 'emotions', text: "Je n'avais pas ressenti ça depuis des années." },
  { id: 1641, theme: 'emotions', text: "Ce sourire-là, il vient de très loin en moi." },
  { id: 1642, theme: 'emotions', text: "Chaque petit progrès me donne envie de continuer." },
  { id: 1643, theme: 'emotions', text: "Tu m'as surpris, et c'était exactement la bonne surprise." },
  { id: 1644, theme: 'emotions', text: "Une douce tristesse, comme la fin d'un très bon film." },
  { id: 1645, theme: 'emotions', text: "Je déborde d'envie de partager ça avec tout le monde." },
  { id: 1646, theme: 'emotions', text: "Ce moment suspendu, j'aimerais qu'il ne finisse jamais." },
  { id: 1647, theme: 'emotions', text: "Quelque chose de léger flotte dans l'air ce matin." },
  { id: 1648, theme: 'emotions', text: "J'espère encore, et cet espoir me suffit pour avancer." },
  { id: 1649, theme: 'emotions', text: "C'est drôle comme certains instants restent gravés pour toujours." },

  // Histoires courtes (1700–1749)
  { id: 1700, theme: 'histoires', text: "En rentrant du marché, elle s'est souvenue d'avoir oublié le pain et a fait demi-tour sans hésiter." },
  { id: 1701, theme: 'histoires', text: "Il a ouvert la fenêtre et respiré l'air du matin avant de commencer sa journée." },
  { id: 1702, theme: 'histoires', text: "On avait prévu un pique-nique, mais la pluie a tout changé et on a fini par cuisiner ensemble." },
  { id: 1703, theme: 'histoires', text: "Elle cherchait ses clés depuis dix minutes quand elle les a trouvées dans sa poche de manteau." },
  { id: 1704, theme: 'histoires', text: "Le chat s'était endormi sur le journal, et personne n'osait le déranger." },
  { id: 1705, theme: 'histoires', text: "Nous avons raté notre train de quelques secondes et avons découvert un café charmant en attendant le suivant." },
  { id: 1706, theme: 'histoires', text: "Il pleuvait fort quand il a aperçu un parapluie oublié sur un banc et l'a pris avec un sourire coupable." },
  { id: 1707, theme: 'histoires', text: "Elle a allumé une bougie, ouvert son livre, et a passé toute la soirée sans regarder son téléphone." },
  { id: 1708, theme: 'histoires', text: "On s'est perdus dans le quartier et on a découvert une ruelle fleurie qu'on n'aurait jamais trouvée autrement." },
  { id: 1709, theme: 'histoires', text: "Il a commandé un café, s'est assis près de la vitre et a regardé les passants pendant une heure entière." },
  { id: 1710, theme: 'histoires', text: "Elle avait oublié l'anniversaire de sa voisine, alors elle lui a offert des fleurs cueillies dans son propre jardin." },
  { id: 1711, theme: 'histoires', text: "Nous avons commencé à repeindre la cuisine un samedi matin et n'avons pas pu s'arrêter avant la nuit." },
  { id: 1712, theme: 'histoires', text: "Il a trouvé une vieille photo dans un tiroir et a souri en reconnaissant un visage qu'il n'avait pas vu depuis des années." },
  { id: 1713, theme: 'histoires', text: "Elle a préparé une soupe avec les restes du frigo et c'était finalement le meilleur repas de la semaine." },
  { id: 1714, theme: 'histoires', text: "On traversait la forêt quand un écureuil est passé en courant juste devant nos pieds." },
  { id: 1715, theme: 'histoires', text: "Il a envoyé un message à la mauvaise personne, puis a passé cinq minutes à trouver comment s'expliquer." },
  { id: 1716, theme: 'histoires', text: "Elle a planté des tomates au printemps et les a regardées pousser avec une fierté inattendue tout l'été." },
  { id: 1717, theme: 'histoires', text: "Nous nous sommes levés à l'aube pour voir le lever du soleil et sommes rentrés affamés mais heureux." },
  { id: 1718, theme: 'histoires', text: "Il lisait son livre dans le parc quand un enfant est venu lui demander si le banc était libre." },
  { id: 1719, theme: 'histoires', text: "Elle a reçu une lettre manuscrite dans sa boîte aux lettres et l'a lue deux fois, debout dans le couloir." },
  { id: 1720, theme: 'histoires', text: "On avait marché si longtemps que, de retour chez nous, on s'est endormis avant même de dîner." },
  { id: 1721, theme: 'histoires', text: "Il a renversé son café sur ses notes et a passé la matinée à déchiffrer des mots brouillés." },
  { id: 1722, theme: 'histoires', text: "Elle a essayé une nouvelle recette de gâteau qui a brûlé, et elle a recommencé sans se décourager." },
  { id: 1723, theme: 'histoires', text: "Nous avons rencontré un vieil ami par hasard dans la rue et avons parlé debout pendant une heure." },
  { id: 1724, theme: 'histoires', text: "Il regardait tomber les feuilles depuis sa fenêtre quand il a décidé de sortir marcher une dernière fois avant l'hiver." },
  { id: 1725, theme: 'histoires', text: "Elle a appris à faire du vélo à quarante ans, sous les encouragements de ses enfants qui couraient à côté." },
  { id: 1726, theme: 'histoires', text: "On a joué aux cartes toute la nuit et, au matin, personne ne se rappelait plus qui avait gagné." },
  { id: 1727, theme: 'histoires', text: "Il a acheté un cadre pour une affiche, mais la photo de sa famille lui a semblé bien mieux à la place." },
  { id: 1728, theme: 'histoires', text: "Elle a raté son arrêt de bus en lisant et a découvert un nouveau quartier en marchant pour rentrer." },
  { id: 1729, theme: 'histoires', text: "Nous avons décidé de ne pas planifier nos vacances et avons simplement suivi les panneaux que l'on trouvait beaux." },
  { id: 1730, theme: 'histoires', text: "Il a cuisiné pour la première fois tout seul et a appelé sa mère pour lui annoncer la nouvelle." },
  { id: 1731, theme: 'histoires', text: "Elle a trouvé un vieux carnet de voyage au fond d'un carton et a relu chaque page avec nostalgie." },
  { id: 1732, theme: 'histoires', text: "On s'est mis d'accord pour ne pas offrir de cadeaux cette année, mais tout le monde en a apporté quand même." },
  { id: 1733, theme: 'histoires', text: "Il a commencé à apprendre la guitare, et ses voisins ont eu la patience de ne rien dire pendant des semaines." },
  { id: 1734, theme: 'histoires', text: "Elle a regardé un film qu'elle avait vu enfant et ne se souvenait que de la fin, qu'elle avait bien mal comprise." },
  { id: 1735, theme: 'histoires', text: "Nous avons planté un arbre dans le jardin pour marquer l'occasion, et nous l'arrosons chaque matin depuis." },
  { id: 1736, theme: 'histoires', text: "Il a passé une heure à chercher ses lunettes avant de réaliser qu'il les portait déjà sur le nez." },
  { id: 1737, theme: 'histoires', text: "Elle a décidé de prendre le chemin le plus long pour rentrer, et c'était exactement ce dont elle avait besoin." },
  { id: 1738, theme: 'histoires', text: "On a commandé une pizza en croyant que c'était une soirée ordinaire, et ce fut la meilleure soirée du mois." },
  { id: 1739, theme: 'histoires', text: "Il a trouvé un billet de vingt euros dans une vieille veste et a décidé de l'offrir à quelqu'un dans le besoin." },
  { id: 1740, theme: 'histoires', text: "Elle chantonnait sans s'en rendre compte, et c'est son collègue qui lui a fait remarquer avec un grand sourire." },
  { id: 1741, theme: 'histoires', text: "Nous avons construit une cabane dans le jardin un week-end entier, et elle a tenu deux ans avant de s'effondrer doucement." },
  { id: 1742, theme: 'histoires', text: "Il a raté la première marche en sortant du métro et a regardé autour de lui pour vérifier que personne n'avait vu." },
  { id: 1743, theme: 'histoires', text: "Elle a glissé un mot doux dans la poche de son manteau pour le retrouver plus tard, un jour de cafard." },
  { id: 1744, theme: 'histoires', text: "On a essayé de cultiver des herbes aromatiques sur le balcon, et seul le basilic a survécu à notre négligence." },
  { id: 1745, theme: 'histoires', text: "Il s'est réveillé en pleine nuit, convaincu d'avoir oublié quelque chose d'important, et s'est rendormi sans trouver quoi." },
  { id: 1746, theme: 'histoires', text: "Elle a appris par cœur un poème pour surprendre son ami à son anniversaire, et a oublié la moitié au dernier moment." },
  { id: 1747, theme: 'histoires', text: "Nous avons regardé les étoiles allongés dans l'herbe et nous sommes disputés gentiment sur les noms des constellations." },
  { id: 1748, theme: 'histoires', text: "Il a passé une journée entière sans internet et a réalisé que ça ne lui avait pas autant manqué que prévu." },
  { id: 1749, theme: 'histoires', text: "Elle a offert un livre qu'elle adorait à une inconnue dans le train, parce que ça lui semblait juste." },

  // Virelangues (1800–1849)
  { id: 1800, theme: 'virelangues', text: "Un chasseur sachant chasser sait chasser sans son chien de chasse." },
  { id: 1801, theme: 'virelangues', text: "La rivière roule ses rochers ronds sur les rives rocailleuses et rugueuses." },
  { id: 1802, theme: 'virelangues', text: "Six cents saucissons secs sur six cents saucissonniers sèchent sous le soleil." },
  { id: 1803, theme: 'virelangues', text: "Papa pèle proprement peu de petits pois bien pâles et potelés." },
  { id: 1804, theme: 'virelangues', text: "Le chien cherche la chaise du chercheur chaleureux dans la chambre close." },
  { id: 1805, theme: 'virelangues', text: "Tu t'entêtes à tenter de tâtonner dans les ténèbres touffues et tordues." },
  { id: 1806, theme: 'virelangues', text: "Didon dîna dit-on du dos d'un dodu dindon doré et délicieux." },
  { id: 1807, theme: 'virelangues', text: "Trois gros rats gris dans trois grands trous ronds grattent le grès." },
  { id: 1808, theme: 'virelangues', text: "Ces cerises sont-elles sur cette selle de cet assesseur insouciant ?" },
  { id: 1809, theme: 'virelangues', text: "Le fisc fixe exprès chaque taxe fiscale excessive à ce faux frais." },
  { id: 1810, theme: 'virelangues', text: "Natacha n'attacha pas son chat Pacha qui s'échappa par la chatière." },
  { id: 1811, theme: 'virelangues', text: "Combien de sous sont ces saucissons-ci ? Ces saucissons-ci sont six sous." },
  { id: 1812, theme: 'virelangues', text: "Le libraire Lalonde relie les livres lents et les lourds volumes lus." },
  { id: 1813, theme: 'virelangues', text: "Seize jacinthes sèchent dans seize caisses depuis six semaines sous la serre." },
  { id: 1814, theme: 'virelangues', text: "Bernard vend du vert verre, du vrai verre vert, du beau verre vert." },
  { id: 1815, theme: 'virelangues', text: "Le muet meurt mais le mou moud toujours le mil dans le moulin." },
  { id: 1816, theme: 'virelangues', text: "Branle-bas de combat, bras ballants, bâtons brisés, bateaux bossués bringuebalants." },
  { id: 1817, theme: 'virelangues', text: "Cinq chiens cherchent cinq cents chatons cachés dans cinq grandes chaumières chaudes." },
  { id: 1818, theme: 'virelangues', text: "Ton thé t'a-t-il ôté ta toux ? Oui, ton thé m'a ôté ma toux." },
  { id: 1819, theme: 'virelangues', text: "Le dragon dragonne et dégringole dans la drague dure du donjon de droite." },
  { id: 1820, theme: 'virelangues', text: "La boulangère beurre de belles brioches bien brunes et bien bombées." },
  { id: 1821, theme: 'virelangues', text: "Pauvre petit pêcheur, prends patience, pour peu que le poisson parte promptement." },
  { id: 1822, theme: 'virelangues', text: "En entendant l'encens, l'enfant innocent s'endort en entonnant son ancienne antienne." },
  { id: 1823, theme: 'virelangues', text: "Grenouilles grises grimpent sur les grilles grugées du grand grillage grinçant." },
  { id: 1824, theme: 'virelangues', text: "Sophie surgit de derrière le sofa, sourit, soupira, puis se rassit sans bruit." },
  { id: 1825, theme: 'virelangues', text: "Je veux et j'exige d'exquises excuses justement justifiées et joliment formulées." },
  { id: 1826, theme: 'virelangues', text: "Trente-trois trains transportent treize truites très trapues et trois gros thons tachetés." },
  { id: 1827, theme: 'virelangues', text: "Les chaussettes de l'archiduchesse sont-elles sèches ? Archi-sèches, archi-séchées." },
  { id: 1828, theme: 'virelangues', text: "Nul ne connaît le nom ni le nombre de noix noires nommées par Nina." },
  { id: 1829, theme: 'virelangues', text: "Prunier qui produit peu de prunes est un pauvre petit prunier peu productif." },
  { id: 1830, theme: 'virelangues', text: "Léa rêve de lire librement les longs livres de la librairie lumineuse de Lyon." },
  { id: 1831, theme: 'virelangues', text: "Gros gras grand grain d'orge, tout gros gras grand grain d'orge qu'il est encore." },
  { id: 1832, theme: 'virelangues', text: "La cavale de la valse avale la cave dans la valse du cavalier cavalant." },
  { id: 1833, theme: 'virelangues', text: "Cet été, ta tante timide titubait en trottinant sur les trottoirs tordus de Tours." },
  { id: 1834, theme: 'virelangues', text: "Sous le pont du port de Toulon dort un gros taureau tout en rondeur." },
  { id: 1835, theme: 'virelangues', text: "Le pied plat du plâtrier plâtre et replâtre le plafond plat de la plaine." },
  { id: 1836, theme: 'virelangues', text: "Voici six vieilles violettes volées à la Villa Violette par Viviane la vivante." },
  { id: 1837, theme: 'virelangues', text: "Le crabe croque la crevette crue cramponnée contre le creux de la crique." },
  { id: 1838, theme: 'virelangues', text: "Ma mie Mimie aime mimer la mimique de l'ami Mimi dans la mi-nuit." },
  { id: 1839, theme: 'virelangues', text: "Cantatrice, chanteuse et chanteur chantent cent chansons chaudes dans chaque chambre." },
  { id: 1840, theme: 'virelangues', text: "Un ange enjambait l'enjeu des anges enchantés entendant d'anciens airs anciens." },
  { id: 1841, theme: 'virelangues', text: "Sacha sèche ses chaussures sur le seuil du château de la Sarre et sourit." },
  { id: 1842, theme: 'virelangues', text: "Quatorze crocodiles croulants croisent des croupiers courbés au crépuscule craquant." },
  { id: 1843, theme: 'virelangues', text: "Le grand verglas glacé de Grenoble a gelé les galettes grasses du glacier gris." },
  { id: 1844, theme: 'virelangues', text: "Dormir debout dans du drap dru donne des douleurs dans le dos droit." },
  { id: 1845, theme: 'virelangues', text: "Mimi murmure à mi-mots des mots mous à sa mémé mélancolique de Montmartre." },
  { id: 1846, theme: 'virelangues', text: "La pie niche haut, le hibou niche bas, où niche-t-elle la chouette ? En bas." },
  { id: 1847, theme: 'virelangues', text: "La froide friture de la friteuse frit franchement froid en froissant les frères." },
  { id: 1848, theme: 'virelangues', text: "Fifi Lafitte fait frémir la fête en flûtant follement des fables fort festives." },
  { id: 1849, theme: 'virelangues', text: "Zazou zézaie en zigzaguant dans la zone zébrée de la gare de Zurich." },
]

export const getPhrasesByTheme = (theme: PhraseTheme): readonly Phrase[] =>
  PHRASES.filter(p => p.theme === theme)

export const getRandomPhrase = (exclude?: number, theme?: PhraseTheme): Phrase => {
  const pool = PHRASES.filter(p => (theme === undefined || p.theme === theme) && p.id !== exclude)
  const safe = pool.length > 0 ? pool : PHRASES.filter(p => theme === undefined || p.theme === theme)
  return safe[Math.floor(Math.random() * safe.length)] ?? PHRASES[0]!
}
